--------------------------------------------------------
--  DDL for Table ELE_DOCUMENTO_ELECTRONICO
--------------------------------------------------------
--DROP TABLE ELE_DOCUMENTO_ELECTRONICO;
  CREATE TABLE "ELE_DOCUMENTO_ELECTRONICO" 
   (	"ID" NUMBER, 
	"CODIGO" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"NUMERO_AUTORIZACION" VARCHAR2(100 BYTE), 
	"FECHA_AUTORIZACION" VARCHAR2(100 BYTE), 
	"OBSERVACION" VARCHAR2(4000 BYTE), 
	"ESTADO" VARCHAR2(10 BYTE)
   )  TABLESPACE "DATOS" ;
--------------------------------------------------------
--  DDL for Index PK_ELE_DOCUMENTO_ELECTRONICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ELE_DOCUMENTO_ELECTRONICO" ON "ELE_DOCUMENTO_ELECTRONICO" ("ID") 
  TABLESPACE "INDICES" ;
--------------------------------------------------------
--  DDL for Index UK_ELE_DOCUMENTO_ELECTRONICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_ELE_DOCUMENTO_ELECTRONICO" ON "ELE_DOCUMENTO_ELECTRONICO" ("CODIGO", "NUMERO") 
   TABLESPACE "INDICES" ;
--------------------------------------------------------
--  Constraints for Table ELE_DOCUMENTO_ELECTRONICO
--------------------------------------------------------

  ALTER TABLE "ELE_DOCUMENTO_ELECTRONICO" ADD CONSTRAINT "UK_ELE_DOCUMENTO_ELECTRONICO" UNIQUE ("CODIGO", "NUMERO")
  USING INDEX   TABLESPACE "INDICES"  ENABLE;
  ALTER TABLE "ELE_DOCUMENTO_ELECTRONICO" ADD CONSTRAINT "PK_ELE_DOCUMENTO_ELECTRONICO" PRIMARY KEY ("ID")
  USING INDEX   TABLESPACE "INDICES"  ENABLE;
  ALTER TABLE "ELE_DOCUMENTO_ELECTRONICO" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "ELE_DOCUMENTO_ELECTRONICO" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "ELE_DOCUMENTO_ELECTRONICO" MODIFY ("ID" NOT NULL ENABLE);
