--------------------------------------------------------
--  DDL for Table SRI_DETALLE_ANULADO
--------------------------------------------------------

  CREATE TABLE "SRI_DETALLE_ANULADO" 
   (	"ID" NUMBER, 
	"IDINFORMANTE" VARCHAR2(20 BYTE), 
	"ANIO" VARCHAR2(20 BYTE), 
	"MES" VARCHAR2(10 BYTE), 
	"CODIGO" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"TIPOCOMPROBANTE" VARCHAR2(20 BYTE), 
	"ESTABLECIMIENTO" VARCHAR2(20 BYTE), 
	"PUNTOEMISION" VARCHAR2(20 BYTE), 
	"SECUENCIALINICIO" VARCHAR2(20 BYTE), 
	"SECUENCIALFIN" VARCHAR2(20 BYTE), 
	"AUTORIZACION" VARCHAR2(100 BYTE)
   )  TABLESPACE "DATOS" ;
