--------------------------------------------------------
--  DDL for Table SRI_RETENCION
--------------------------------------------------------

  CREATE TABLE "SRI_RETENCION" 
   (	"ID_DETALLE_COMPRA" NUMBER, 
	"ESTABRETENCION1" VARCHAR2(10 BYTE), 
	"PTOEMIRETENCION1" VARCHAR2(10 BYTE), 
	"SECRETENCION1" VARCHAR2(20 BYTE), 
	"AUTRETENCION1" VARCHAR2(100 BYTE), 
	"FECHAEMIRET1" DATE
   )  TABLESPACE "DATOS" ;
--------------------------------------------------------
--  Constraints for Table SRI_RETENCION
--------------------------------------------------------

  ALTER TABLE "SRI_RETENCION" MODIFY ("FECHAEMIRET1" NOT NULL ENABLE);
  ALTER TABLE "SRI_RETENCION" MODIFY ("AUTRETENCION1" NOT NULL ENABLE);
  ALTER TABLE "SRI_RETENCION" MODIFY ("SECRETENCION1" NOT NULL ENABLE);
  ALTER TABLE "SRI_RETENCION" MODIFY ("PTOEMIRETENCION1" NOT NULL ENABLE);
  ALTER TABLE "SRI_RETENCION" MODIFY ("ESTABRETENCION1" NOT NULL ENABLE);
  ALTER TABLE "SRI_RETENCION" MODIFY ("ID_DETALLE_COMPRA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SRI_RETENCION
--------------------------------------------------------

  ALTER TABLE "SRI_RETENCION" ADD CONSTRAINT "FK_SRI_RETENCION" FOREIGN KEY ("ID_DETALLE_COMPRA")
	  REFERENCES "SRI_DETALLE_COMPRA" ("ID") ON DELETE CASCADE ENABLE;
