--------------------------------------------------------
--  DDL for Table SRI_DETALLE_VENTA
--------------------------------------------------------

  CREATE TABLE "SRI_DETALLE_VENTA" 
   (	"ID" NUMBER, 
	"IDINFORMANTE" VARCHAR2(20 BYTE), 
	"ANIO" VARCHAR2(10 BYTE), 
	"MES" VARCHAR2(10 BYTE), 
	"TPIDCLIENTE" VARCHAR2(10 BYTE), 
	"IDCLIENTE" VARCHAR2(20 BYTE), 
	"PARTERELVTAS" VARCHAR2(10 BYTE), 
	"TIPOCOMPROBANTE" VARCHAR2(10 BYTE), 
	"TIPOEMISION" VARCHAR2(10 BYTE), 
	"NUMEROCOMPROBANTES" VARCHAR2(10 BYTE), 
	"BASENOGRAIVA" NUMBER DEFAULT 0, 
	"BASEIMPONIBLE" NUMBER DEFAULT 0, 
	"BASEIMPGRAV" NUMBER DEFAULT 0, 
	"MONTOIVA" NUMBER DEFAULT 0, 
	"MONTOICE" NUMBER DEFAULT 0, 
	"VALORRETIVA" NUMBER DEFAULT 0, 
	"VALORRETRENTA" NUMBER DEFAULT 0, 
	"TIPOCLIENTE" VARCHAR2(10 BYTE) DEFAULT '01', 
	"DENOCLI" VARCHAR2(200 BYTE)
   )  TABLESPACE "DATOS" ;

   COMMENT ON COLUMN "SRI_DETALLE_VENTA"."TIPOCLIENTE" IS 'Para los clientes con pasaporte';
   COMMENT ON COLUMN "SRI_DETALLE_VENTA"."DENOCLI" IS 'Para los clientes con pasaporte';
--------------------------------------------------------
--  DDL for Index PK_SRI_DETALLE_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SRI_DETALLE_VENTA" ON "SRI_DETALLE_VENTA" ("ID") 
  TABLESPACE "INDICES" ;
--------------------------------------------------------
--  Constraints for Table SRI_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "SRI_DETALLE_VENTA" ADD CONSTRAINT "PK_SRI_DETALLE_VENTA" PRIMARY KEY ("ID")
  USING INDEX TABLESPACE "INDICES"  ENABLE;
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("VALORRETRENTA" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("VALORRETIVA" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("MONTOICE" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("MONTOIVA" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("BASEIMPGRAV" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("BASEIMPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("BASENOGRAIVA" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("NUMEROCOMPROBANTES" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("TIPOEMISION" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("TIPOCOMPROBANTE" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("PARTERELVTAS" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("TPIDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("IDINFORMANTE" NOT NULL ENABLE);
  ALTER TABLE "SRI_DETALLE_VENTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SRI_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "SRI_DETALLE_VENTA" ADD CONSTRAINT "FK_SRI_DETALLE_VENTA" FOREIGN KEY ("IDINFORMANTE")
	  REFERENCES "SRI_INFORMANTE" ("IDINFORMANTE") ON DELETE CASCADE ENABLE;
