--------------------------------------------------------
--  DDL for Table SRI_REEMBOLSO
--------------------------------------------------------

  CREATE TABLE "SRI_REEMBOLSO" 
   (	"ID_DETALLE_COMPRA" NUMBER, 
	"TIPOCOMPROBANTEREEMB" VARCHAR2(20 BYTE), 
	"TPIDPROVREEMB" VARCHAR2(20 BYTE), 
	"IDPROVREEMB" VARCHAR2(20 BYTE), 
	"ESTABLECIMIENTOREEMB" VARCHAR2(20 BYTE), 
	"PUNTOEMISIONREEMB" VARCHAR2(20 BYTE), 
	"SECUENCIALREEMB" VARCHAR2(20 BYTE), 
	"FECHAEMISIONREEMB" DATE, 
	"AUTORIZACIONREEMB" VARCHAR2(100 BYTE), 
	"BASEIMPONIBLEREEMB" NUMBER DEFAULT 0, 
	"BASEIMPGRAVREEMB" NUMBER DEFAULT 0, 
	"BASENOGRAIVAREEMB" NUMBER DEFAULT 0, 
	"BASEIMPEXEREEMB" NUMBER DEFAULT 0, 
	"MONTOICEREMB" NUMBER DEFAULT 0, 
	"MONTOIVAREMB" NUMBER DEFAULT 0
   )   TABLESPACE "DATOS" ;
--------------------------------------------------------
--  Constraints for Table SRI_REEMBOLSO
--------------------------------------------------------

  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("MONTOIVAREMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("MONTOICEREMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("BASEIMPEXEREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("BASENOGRAIVAREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("BASEIMPGRAVREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("BASEIMPONIBLEREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("AUTORIZACIONREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("FECHAEMISIONREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("SECUENCIALREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("PUNTOEMISIONREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("ESTABLECIMIENTOREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("IDPROVREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("TPIDPROVREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("TIPOCOMPROBANTEREEMB" NOT NULL ENABLE);
  ALTER TABLE "SRI_REEMBOLSO" MODIFY ("ID_DETALLE_COMPRA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SRI_REEMBOLSO
--------------------------------------------------------

  ALTER TABLE "SRI_REEMBOLSO" ADD CONSTRAINT "FK_SRI_REEMBOLSO" FOREIGN KEY ("ID_DETALLE_COMPRA")
	  REFERENCES "SRI_DETALLE_COMPRA" ("ID") ON DELETE CASCADE ENABLE;
