--------------------------------------------------------
--  DDL for Table SRI_PAGO_EXTERIOR
--------------------------------------------------------

  CREATE TABLE "SRI_PAGO_EXTERIOR" 
   (	"ID_DETALLE_COMPRA" NUMBER, 
	"PAGOLOCEXT" VARCHAR2(20 BYTE) DEFAULT '01', 
	"PAISEFECPAGO" VARCHAR2(20 BYTE) DEFAULT 'NA', 
	"APLICCONVDOBTRIB" VARCHAR2(20 BYTE) DEFAULT 'NA', 
	"PAGEXTSUJRETNORLEG" VARCHAR2(20 BYTE) DEFAULT 'NA'
   ) TABLESPACE "DATOS" ;
--------------------------------------------------------
--  Constraints for Table SRI_PAGO_EXTERIOR
--------------------------------------------------------

  ALTER TABLE "SRI_PAGO_EXTERIOR" MODIFY ("PAGEXTSUJRETNORLEG" NOT NULL ENABLE);
  ALTER TABLE "SRI_PAGO_EXTERIOR" MODIFY ("APLICCONVDOBTRIB" NOT NULL ENABLE);
  ALTER TABLE "SRI_PAGO_EXTERIOR" MODIFY ("PAISEFECPAGO" NOT NULL ENABLE);
  ALTER TABLE "SRI_PAGO_EXTERIOR" MODIFY ("PAGOLOCEXT" NOT NULL ENABLE);
  ALTER TABLE "SRI_PAGO_EXTERIOR" MODIFY ("ID_DETALLE_COMPRA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SRI_PAGO_EXTERIOR
--------------------------------------------------------

  ALTER TABLE "SRI_PAGO_EXTERIOR" ADD CONSTRAINT "FK_SRI_PAGO_EXTERIOR" FOREIGN KEY ("ID_DETALLE_COMPRA")
	  REFERENCES "SRI_DETALLE_COMPRA" ("ID") ON DELETE CASCADE ENABLE;
