--------------------------------------------------------
--  DDL for Table SRI_MODIFICADO
--------------------------------------------------------

  CREATE TABLE "SRI_MODIFICADO" 
   (	"ID_DETALLE_COMPRA" NUMBER, 
	"DOCMODIFICADO" VARCHAR2(10 BYTE), 
	"ESTABMODIFICADO" VARCHAR2(10 BYTE), 
	"PTOEMIMODIFICADO" VARCHAR2(10 BYTE), 
	"SECMODIFICADO" VARCHAR2(10 BYTE), 
	"AUTMODIFICADO" VARCHAR2(100 BYTE)
   ) TABLESPACE "DATOS" ;
--------------------------------------------------------
--  Constraints for Table SRI_MODIFICADO
--------------------------------------------------------

  ALTER TABLE "SRI_MODIFICADO" MODIFY ("AUTMODIFICADO" NOT NULL ENABLE);
  ALTER TABLE "SRI_MODIFICADO" MODIFY ("SECMODIFICADO" NOT NULL ENABLE);
  ALTER TABLE "SRI_MODIFICADO" MODIFY ("PTOEMIMODIFICADO" NOT NULL ENABLE);
  ALTER TABLE "SRI_MODIFICADO" MODIFY ("ESTABMODIFICADO" NOT NULL ENABLE);
  ALTER TABLE "SRI_MODIFICADO" MODIFY ("DOCMODIFICADO" NOT NULL ENABLE);
  ALTER TABLE "SRI_MODIFICADO" MODIFY ("ID_DETALLE_COMPRA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SRI_MODIFICADO
--------------------------------------------------------

  ALTER TABLE "SRI_MODIFICADO" ADD CONSTRAINT "FK_SRI_MODIFICADO" FOREIGN KEY ("ID_DETALLE_COMPRA")
	  REFERENCES "SRI_DETALLE_COMPRA" ("ID") ON DELETE CASCADE ENABLE;
