--------------------------------------------------------
--  DDL for Table SRI_VENTA_ESTABLECIMIENTO
--------------------------------------------------------
--drop table SRI_VENTA_ESTABLECIMIENTO;
  CREATE TABLE "SRI_VENTA_ESTABLECIMIENTO" 
   (	"IDINFORMANTE" VARCHAR2(20 BYTE), 
	"CODESTAB" VARCHAR2(10 BYTE), 
	"VENTASESTAB" NUMBER, 
	"ANIO" VARCHAR2(10 BYTE), 
	"MES" VARCHAR2(10 BYTE)
   )  TABLESPACE "DATOS" ;
--------------------------------------------------------
--  Constraints for Table SRI_VENTA_ESTABLECIMIENTO
--------------------------------------------------------

  ALTER TABLE "SRI_VENTA_ESTABLECIMIENTO" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "SRI_VENTA_ESTABLECIMIENTO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "SRI_VENTA_ESTABLECIMIENTO" MODIFY ("VENTASESTAB" NOT NULL ENABLE);
  ALTER TABLE "SRI_VENTA_ESTABLECIMIENTO" MODIFY ("CODESTAB" NOT NULL ENABLE);
  ALTER TABLE "SRI_VENTA_ESTABLECIMIENTO" MODIFY ("IDINFORMANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SRI_VENTA_ESTABLECIMIENTO
--------------------------------------------------------

  ALTER TABLE "SRI_VENTA_ESTABLECIMIENTO" ADD CONSTRAINT "FK_SRI_VENTA_ESTABLECIMIENTO" FOREIGN KEY ("IDINFORMANTE")
	  REFERENCES "SRI_INFORMANTE" ("IDINFORMANTE") ENABLE;
