ACCEPT usuario CHAR PROMPT 'Nombre del usuario: ';

CREATE USER &USUARIO  PROFILE "DEFAULT" IDENTIFIED BY &PASWORD DEFAULT 
    TABLESPACE "USERS" TEMPORARY 
    TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "ADMINISTRADOR" TO &USUARIO;
GRANT "CONNECT" TO &USUARIO;
GRANT "DBA" TO &USUARIO;
GRANT "EXP_FULL_DATABASE" TO &USUARIO;
GRANT "IMP_FULL_DATABASE" TO &USUARIO;
GRANT ALTER ANY ROLE TO &USUARIO;
GRANT ALTER USER TO &USUARIO;
GRANT CREATE ANY PROCEDURE TO &USUARIO;
GRANT CREATE ROLE TO &USUARIO;
GRANT CREATE USER TO &USUARIO;
GRANT CREATE ANY VIEW TO &USUARIO;
GRANT CREATE PROCEDURE TO &USUARIO;
GRANT CREATE PUBLIC SYNONYM TO &USUARIO;
GRANT DROP ANY ROLE TO &USUARIO;
GRANT DROP USER TO &USUARIO;
GRANT GRANT ANY ROLE TO &USUARIO;

